### ISSUE TITLE
Replace <MASTERIP> with 127.0.0.1 as default IP

### ISSUE THREAD

**Issue by ghost** [OwlH-net/OwlH-UI#34]
Having in mind that by default most installations will have OwIH-UI and OwlH-Master is the same server, it will be preferable to have default IP as 127.0.0.1 in the ui.conf file.
https://github.com/OwlH-net/OwlH-UI/blob/a475058308cf965d4fcfb53c9b6b06770f39aab8/conf/ui.conf#L3

**Comment by 72nomada** [comment]
hi @kennethkaane, 

This doesn't work. Master API and UI must be accessible from the user browser, so Master IP won't be localhost. We are changing that in the new UI version based on nodeJS and React. 

localhost will only work if you use a browser locally to the Master and UI systems.

Does it make sense?

**Comment by ghost** [comment]
Yes, it makes sense but my thinking is since we are still required to update `<MASTERIP>` either manually or via script as with owlhui-httpd.sh, by having it as 127.0.0.1 we will only need to do this step if the installation is not localhost. 

127.0.0.1 can still be changed but I feel it is a better alternative to`<MASTERIP>`. 

https://github.com/OwlH-net/OwlH-UI/blob/a475058308cf965d4fcfb53c9b6b06770f39aab8/conf/service/owlhui-httpd.sh#L24-L25

As in the above case we can do:

`sed -i "s/127.0.0.1/$MYPUBIP/g" /var/www/owlh/conf/ui.conf `

As an example, I have an installation on docker with both OwIH-UI and OwlH-Master ports exposed on 127.0.0.1:443 and 127.0.0.1:50001 respectively. The OwlH-Node is on a public server but sending data to OwlH-Master through OpenVPN, so OwIH-UI and OwlH-Master are completely not accessible publicly which will be the case in most secure installations.

**Comment by 72nomada** [comment]
Hi, how do you access your master? 

OwlH Node won't send data to Master, Master will send orders to Node. Node traffic is sent to wazuh using wazuh agent. 

If you run master API queries using local scripts you won't need master UI. 
if you want to use your master UI you will need to access UI and Master from the same browser. Using 127.0.0.1 means that your master, UI, and browser are in the same machine. 

about sed commands. Both are pretty the same, using <MASTERIP> or 127.0.0.1 in the end they are just strings. we prefer <MASTERIP> as it forces a user to take a look at this configuration and modify it as needed. It is true that script will fail if you are not running on the AWS environment and MASTERIP will be replaced by "" so ip means empty at all. 

Anyway, we know this is not the best configuration ever, we are solving it on the new UI interface. 

thanks a lot

**Comment by ghost** [comment]
Makes a lot of sense now.
